### ISSUE TITLE
Hitting "Back" on the browser does not return to the top

### ISSUE THREAD

**Issue by edoarad** [hamishhuggard/ea_data_viz#2]
I actually didn't understand until now (having rewritten this issue) that this is all in a single page 😊

It'd be great if the navigation would be cleaner. If there'd be a way to get back to the top, and perhaps some breadcrumbs.

**Comment by hamishhuggard** [comment]
Thanks for feedback.

I agree, navigation is quite ad-hoc. I do have plans to improve it in future.
